apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: javajava-java-sample-0qwv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: javajava-java-sample-0qwv
    app.kubernetes.io/part-of: e2e-java
  name: javajava-java-sample-0qwv
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: javajava-java-sample-0qwv
status:
  loadBalancer: {}
